<?php

namespace app\components\behaviors;

use yii\base\Behavior;

class ObjectRelatedBehavior extends Behavior
{
    
    public $sms;
    
    public function __call($name, $params)
    {
        die();
        parent::__call($name, $params);
    }
    
    public function __get($name)
    {
        die();
        return parent::__get($name); // TODO: Change the autogenerated stub
    }
    
    /**
     * @param $name
     * @param bool $throwException
     *
     * @return \yii\db\ActiveQuery|\yii\db\ActiveQueryInterface|null
     */
    public function getRelation($name, $throwException = true)
    {
        $getter = 'get' . $name;
        $class = self::$classes[$name] ?? null;
        
        if (!method_exists($this, $getter) && $class) {
            return $this->hasOne($class, ['id' => 'object_id']);
        }
        
        return parent::getRelation($name, $throwException);
    }
    
}